# Generated by Django 5.1.7 on 2025-03-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
