# Generated by Django 5.1.7 on 2025-03-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuarios_cpf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
