# Generated by Django 5.1.7 on 2025-03-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuarios_cpf_alter_usuarios_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuarios',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='username',
        ),
    ]
